### ISSUE TITLE
代码折叠栏的颜色与背景色混淆

### ISSUE THREAD

**Issue by baoher** [yuhaowow/GeneralConfig#2]
我是用是pycharm的atom主题配色,代码与行号之间有一个箭头，箭头可以折叠代码，但这个箭头的颜色与背景色的颜色一致，会出现两个问题，一个是箭头基本看不到，另一个是代码与linenumber区分不明显，点击断点时容易点击在代码区域。我自己找了很长时间没有找到设置这个颜色的地方，希望作者修复一下，谢谢！

![image](https://user-images.githubusercontent.com/20683694/40714560-8e71c57a-6435-11e8-841e-ced07b613d9b.png)

**Comment by yuhaowow** [comment]
![image](https://user-images.githubusercontent.com/17736182/43942428-8c9a6038-9caa-11e8-82d9-7b3207e1d758.png)
已经修改啦
